header-from: ./.config/header.md

version: ""

formatter: markdown table

name:  terraform-aws-lambda-event-handler-cpu-creditbalance

content: |-
  {{ .Header }}

  # terraform-aws-lambda-event-handler-cpu-creditbalance

  GitHub: [StratusGrid/terraform-aws-lambda-event-handler-cpu-creditbalance](https://github.com/StratusGrid/terraform-aws-lambda-event-handler-cpu-creditbalance)

  This module will deploy a lambda function which will listen for ec2 instance running/stopped/terminated events and put/delete CreditBalance alarms for cpu credits. 
  
  ## Example:
  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - header
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
